Repository webtorrent/webtorrent-desktop, pull requests merged in 2018-10, with the labels that each got.

#1042 save preferences immediately when changed
  package-lock.json
  package.json
  src/renderer/controllers/prefs-controller.js
  src/renderer/pages/preferences-page.js
Labels: enhancement

#1484 fix: replace dependency `open` with `opn`
  bin/open-config.js
  package-lock.json
  package.json
Labels: security

#1494 Bug Fix Empty Array Reduce
  src/renderer/lib/torrent-poster.js
Labels: bug
