Repository webtorrent/webtorrent-desktop, pull requests merged in 2019-10, with the labels that each got.

#1717 Report when files are being verified
  src/renderer/pages/torrent-list-page.js
Labels: area/ux, enhancement

#1719 Update music-metadata to v4.8.0
  package-lock.json
  package.json
Labels: greenkeeper

#1711 Improve codec unsupported detection
  src/main/windows/about.js
  src/main/windows/main.js
  src/main/windows/webtorrent.js
  src/renderer/pages/player-page.js
Labels: enhancement

#1712 Add support for multiple audio tracks
  src/renderer/controllers/audio-tracks-controller.js
  src/renderer/lib/state.js
  src/renderer/main.js
  src/renderer/pages/player-page.js
  static/main.css
Labels: enhancement
