Repository webtorrent/webtorrent-desktop, pull requests merged in 2019-09, with the labels that each got.

#1642 Stop shipping 32-bit binaries
  bin/package.js
Labels: enhancement

#1580 Ignore JetBrains IntelliJ IDEA project files
  .gitignore
Labels: enhancement

#1693 Fix "EPERM: operation not permitted, open 'C:\Users\account\AppData\Local
  package-lock.json
  package.json
  src/renderer/lib/migrations.js
  src/renderer/lib/state.js
  test/setup.js
Labels: bug, platform/windows

#1650 introduce linux arm64 support
  bin/package.js
Labels: accepted, area/packaging, enhancement, platform/linux

#1694 Add rpm package creation support
  README.md
  bin/package.js
  package-lock.json
  package.json
Labels: accepted, area/packaging, enhancement
