Repository webtorrent/webtorrent-desktop, pull requests merged in 2020-07, with the labels that each got.

#1835 Add macOS Notarization
  bin/darwin-entitlements.plist
  bin/package.js
  package.json
Labels: area/packaging, platform/mac

#1847 Update music metadata
  package-lock.json
  package.json
  src/renderer/webtorrent.js
Labels: dependencies

#1845 Fix audio metadata not being displayed
  src/renderer/webtorrent.js
Labels: bug
