Repository webtorrent/webtorrent-desktop, pull requests merged in 2021-09, with the labels that each got.

#1888 build: add package Github Action
  .github/workflows/package.yml
Labels: area/packaging

#1237 Release media keys when opening external player
  src/main/ipc.js
Labels: enhancement, accepted

#1922 Fix ghost image showing on media player drag
  src/renderer/pages/player-page.js
Labels: stale

#997 Ensure that default file/protocol handlers are re-installed after updating.
  src/renderer/lib/migrations.js
Labels: enhancement, accepted
